### ISSUE TITLE
Grafico logaritmico e delle differenze

### ISSUE THREAD

**Issue by giuseppeM99** [hearot/covidlogistic19#1]
Aggiungere un grafico in scala logaritmica e un grafico lineare delle differenze giornaliere

**Comment by hearot** [comment]
Mi pare un'ottima idea!

**Comment by hearot** [comment]
Con https://github.com/hearot/covidlogistic19/commit/811960d6ae1c637c297a47b81dcd65f61dca1032 ho aggiunto la scala logaritmica! 📈

**Comment by giuseppeM99** [comment]
È ancora aperta? Bah

**Comment by giuseppeM99** [comment]
Il grafico a barre non rappresenta le differenze ma il complessivo
